### ISSUE TITLE
make: the '-j' option requires a positive integer argument

### ISSUE THREAD

**Issue by martindorey** [orangepi-xunlong/OrangePiRK3399_scripts#1]
From: Martin Dorey <Martin.Dorey@hitachivantara.com>
Sent: Monday, December 30, 2019 10:45
To: test991199test <test991199test@gmail.com>; bug-make@gnu.org <bug-make@gnu.org>
Subject: Re: orange pi 4B Report bugs
 
From the attachment:

Platform RK3399 is build OK, with new .config(make rk3399_defconfig)
 Complete U-boot compile....
 Start compiling the kernel ...
make: the '-j' option requires a positive integer argument
Usage: make [options] [target] ...

I think that's a bug at:

https://github.com/orangepi-xunlong/OrangePiRK3399_scripts/blob/orangepi_4/build.sh#L31

... which would only occur if you build on a single core machine.  Contrast the extra code to cope with that case at:

https://github.com/orangepi-xunlong/OrangePiRK3399_scripts/blob/1ce1b5f2b719ccfeb896bfc310a1732dabda1ccf/uboot_compile.sh#L25

It's not a bug in make, so this isn't the place to report it.

From: Bug-make <bug-make-bounces+martin.dorey=hds.com@gnu.org> on behalf of test991199test <test991199test@gmail.com>
Sent: Friday, December 27, 2019 10:01
To: bug-make@gnu.org <bug-make@gnu.org>
Subject: orange pi 4B Report bugs
 
***** EXTERNAL EMAIL *****
Hello, 

Report bugs

Can not make ubuntu server for orange pi 4B

Thank you

**Comment by baiywt** [comment]
this issue is fixed by ppiotr3k , it merge into orangepi_4 branch.
